const ProjectValidationRule = {
	DESCRIPTION_MAXIMUM_LENGTH: 1000,
	NAME_MAXIMUM_LENGTH: 50,
	NAME_MINIMUM_LENGTH: 1,
	INPUT_MAXIMUM_LENGTH: 256,
	INPUT_MINIMUM_LENGTH: 1,
} as const;

export { ProjectValidationRule };
